name: Fetch NASA News Articles

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch_articles:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdownify

      # Optional: Clear processed_articles.txt for a clean test run
      # - name: Clear processed articles for testing (REMOVE AFTER FULL TEST)
      #   run: |
      #     echo "Clearing processed_articles.txt for testing"
      #     echo -n "" > processed_articles.txt # Empties the file or creates it if not exists

      - name: Run Fetch NASA Articles Script
        run: python fetch_nasa_articles.py 

      - name: List files after script execution # DEBUGGING STEP
        run: |
          echo "Current directory: $(pwd)"
          echo "--- Listing root directory: ---"
          ls -la
          echo "--- Listing articles directory (if exists): ---"
          ls -la articles/ || echo "articles/ directory not found or empty."
          echo "--- Contents of processed_articles.txt (if exists): ---"
          cat processed_articles.txt || echo "processed_articles.txt not found."

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Ensure articles directory exists before trying to add it, to prevent error if no articles found
          mkdir -p articles 
          
          git add articles/ processed_articles.txt
          
          if git diff --staged --quiet; then
            echo "No new articles or changes to commit."
          else
            echo "Changes detected. Committing and pushing..."
            git commit -m "Automated: Update NASA news articles"
            git push
            echo "Push successful."
          fi
